name: Workflow for Codecov example-node
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm test
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage to Codecov (arg token)
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Upload coverage to Codecov (oidc)
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          use_oidc: true
          verbose: true
